name: Test Automation Hooks

on:
  workflow_dispatch:  # Manual trigger only
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e-test-suite:
    name: Comprehensive E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run E2E Test Suite
        run: |
          chmod +x tests/e2e-test-suite.sh
          ./tests/e2e-test-suite.sh

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            /tmp/claude-automation-e2e-test-*/
          retention-days: 7
